
import java.io.File;
import java.util.Scanner;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sourav
 */
public class Dash extends javax.swing.JFrame {

    /**
     * Creates new form Dash
     */
    public Dash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        client1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        client2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        client3 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        dash7 = new javax.swing.JPanel();
        dash1 = new javax.swing.JPanel();
        dash2 = new javax.swing.JPanel();
        dash3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dash4 = new javax.swing.JPanel();
        dash5 = new javax.swing.JPanel();
        dash6 = new javax.swing.JPanel();
        dash8 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(32, 119, 32));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Due");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 100, 30));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("URW Chancery L", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 180, -1));

        client1.setBackground(new java.awt.Color(255, 255, 255));
        client1.setIcon(new javax.swing.ImageIcon("/home/sourav/Downloads/add new patient.png")); // NOI18N
        client1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client1ActionPerformed(evt);
            }
        });
        jPanel1.add(client1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 70, 60));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 190, 20));

        client2.setBackground(new java.awt.Color(255, 255, 255));
        client2.setIcon(new javax.swing.ImageIcon("/home/sourav/Downloads/add new patient.png")); // NOI18N
        client2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client2ActionPerformed(evt);
            }
        });
        jPanel1.add(client2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 70, 60));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 190, 20));

        client3.setBackground(new java.awt.Color(255, 255, 255));
        client3.setIcon(new javax.swing.ImageIcon("/home/sourav/Downloads/add new patient.png")); // NOI18N
        client3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client3ActionPerformed(evt);
            }
        });
        jPanel1.add(client3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 70, 60));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 190, 20));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(32, 119, 32));
        jTextField2.setFont(new java.awt.Font("URW Chancery L", 1, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("          MST.Tanzina akter");
        jTextField2.setBorder(null);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 180, 20));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(32, 119, 32));
        jTextField3.setFont(new java.awt.Font("URW Chancery L", 1, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("Bablur Rahman");
        jTextField3.setBorder(null);
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 190, 20));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(32, 119, 32));
        jTextField4.setFont(new java.awt.Font("URW Chancery L", 1, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setText("MD.Habibul Basar");
        jTextField4.setBorder(null);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 190, 20));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N

        dash7.setBackground(new java.awt.Color(51, 153, 0));
        jPanel2.add(dash7);

        dash1.setBackground(new java.awt.Color(255, 51, 255));
        jPanel2.add(dash1);

        dash2.setBackground(new java.awt.Color(51, 0, 255));
        jPanel2.add(dash2);

        dash3.setBackground(new java.awt.Color(204, 0, 51));
        jPanel2.add(dash3);

        jLabel3.setBackground(new java.awt.Color(51, 255, 255));
        jLabel3.setFont(new java.awt.Font("URW Chancery L", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("DASHBOARD");
        jLabel3.setBorder(null);
        jLabel3.setMaximumSize(new java.awt.Dimension(70, 15));
        jLabel3.setPreferredSize(new java.awt.Dimension(220, 47));
        jPanel2.add(jLabel3);

        dash4.setBackground(new java.awt.Color(0, 255, 204));
        jPanel2.add(dash4);

        dash5.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.add(dash5);

        dash6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.add(dash6);

        dash8.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.add(dash8);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 520, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setBackground(new java.awt.Color(32, 119, 32));
        jButton2.setFont(new java.awt.Font("URW Chancery L", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add Client");
        jButton2.setPreferredSize(new java.awt.Dimension(120, 36));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jButton1.setBackground(new java.awt.Color(32, 119, 32));
        jButton1.setFont(new java.awt.Font("URW Chancery L", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Edit");
        jButton1.setPreferredSize(new java.awt.Dimension(120, 36));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jTextField5.setBackground(new java.awt.Color(102, 255, 255));
        jTextField5.setFont(new java.awt.Font("URW Chancery L", 1, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(0, 0, 0));
        jTextField5.setPreferredSize(new java.awt.Dimension(120, 27));
        jPanel3.add(jTextField5);

        jButton3.setBackground(new java.awt.Color(32, 119, 32));
        jButton3.setFont(new java.awt.Font("URW Chancery L", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Search");
        jButton3.setPreferredSize(new java.awt.Dimension(120, 36));
        jPanel3.add(jButton3);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 520, 50));

        jLabel4.setBackground(new java.awt.Color(0, 153, 0));
        jLabel4.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Client List");
        jLabel4.setBorder(null);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, 40));

        jButton4.setBackground(new java.awt.Color(32, 119, 32));
        jButton4.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Log Out");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 130, -1));

        jButton5.setBackground(new java.awt.Color(32, 119, 32));
        jButton5.setFont(new java.awt.Font("URW Chancery L", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 550));

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/sourav/Downloads/resize-1628346799232841519backgroundtemplatewithmandalapatterndesign130843584.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void client1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client1ActionPerformed
        info3 obj3=new info3("Bablur Rahman",15,1855888888L,"Male","Dhaka","Islam","AB-",1000); ///This might from a form........
        calculate ob3=new calculate(1000);
       clientpage ob=new clientpage();
       ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_client1ActionPerformed

    private void client2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client2ActionPerformed

       info obj1=new info("MD.Habibul Basar",23,1788888888L,"Male","Dhaka","Islam","AB+",2500); ///This might from a form........
        calculate ob3=new calculate(2500);
       clientpage ob=new clientpage();
       ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_client2ActionPerformed

    private void client3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client3ActionPerformed
       info2 obj2=new info2("MST.Tanzina Akter",21,1755888888L,"Female","Dhaka","Islam","B+",3000); ///This might from a form........
       calculate ob3=new calculate(3000);
       
       clientpage ob=new clientpage();
       ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_client3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       int a = JOptionPane.showConfirmDialog(null,"Are you Sure?","Select",JOptionPane.YES_NO_OPTION);
             if(a==0){
                 NewJFrameforhalkhata ob=new NewJFrameforhalkhata();
                 ob.setVisible(true);
                 dispose();
             }  
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        long total=0;  
        try{
        File f5=new File("total.txt");
        Scanner input=new Scanner(f5);
     
        while(input.hasNext()){
           // num+=input.nextLine()+"\r\n";//for only num pura string
            total=Long.parseLong(input.nextLine());
        }
           // System.out.println(name);
           //System.out.println(username);
           //System.out.println(password);
              
    }
    catch(Exception ex){
        System.out.println("Not found");
    }
       jTextField1.setText(String.valueOf(total));
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton client1;
    private javax.swing.JButton client2;
    private javax.swing.JButton client3;
    private javax.swing.JPanel dash1;
    private javax.swing.JPanel dash2;
    private javax.swing.JPanel dash3;
    private javax.swing.JPanel dash4;
    private javax.swing.JPanel dash5;
    private javax.swing.JPanel dash6;
    private javax.swing.JPanel dash7;
    private javax.swing.JPanel dash8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
