
import java.io.File;
import java.io.FileWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sourav
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regipanel = new javax.swing.JPanel();
        regipanel2 = new javax.swing.JPanel();
        regisname = new javax.swing.JTextField();
        nameregi = new javax.swing.JLabel();
        reginame = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        regiusername = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        regipass = new javax.swing.JLabel();
        regipassword = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        homelevel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regipanel.setBackground(new java.awt.Color(255, 51, 51));

        regipanel2.setBackground(new java.awt.Color(0, 51, 51));

        regisname.setEditable(false);
        regisname.setBackground(new java.awt.Color(0, 51, 51));
        regisname.setFont(new java.awt.Font("URW Chancery L", 1, 36)); // NOI18N
        regisname.setForeground(new java.awt.Color(255, 255, 255));
        regisname.setText("  Registration");
        regisname.setBorder(null);
        regisname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisnameActionPerformed(evt);
            }
        });

        nameregi.setBackground(new java.awt.Color(0, 51, 51));
        nameregi.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        nameregi.setForeground(new java.awt.Color(255, 255, 255));
        nameregi.setText("Name");
        nameregi.setBorder(null);

        reginame.setBackground(new java.awt.Color(0, 51, 51));
        reginame.setFont(new java.awt.Font("URW Chancery L", 1, 18)); // NOI18N
        reginame.setForeground(new java.awt.Color(21, 174, 51));
        reginame.setText("Enter Name");
        reginame.setBorder(null);
        reginame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reginameActionPerformed(evt);
            }
        });

        jSeparator1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        jLabel1.setBorder(null);

        regiusername.setBackground(new java.awt.Color(0, 51, 51));
        regiusername.setFont(new java.awt.Font("URW Chancery L", 1, 18)); // NOI18N
        regiusername.setForeground(new java.awt.Color(21, 174, 51));
        regiusername.setText("Enter Username");
        regiusername.setBorder(null);
        regiusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regiusernameActionPerformed(evt);
            }
        });

        regipass.setBackground(new java.awt.Color(0, 51, 51));
        regipass.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        regipass.setForeground(new java.awt.Color(255, 255, 255));
        regipass.setText("Password");
        regipass.setBorder(null);

        regipassword.setBackground(new java.awt.Color(0, 51, 51));
        regipassword.setFont(new java.awt.Font("URW Chancery L", 1, 18)); // NOI18N
        regipassword.setForeground(new java.awt.Color(21, 174, 51));
        regipassword.setText("Enter Password");
        regipassword.setBorder(null);
        regipassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regipasswordActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("URW Chancery L", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Done ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout regipanel2Layout = new javax.swing.GroupLayout(regipanel2);
        regipanel2.setLayout(regipanel2Layout);
        regipanel2Layout.setHorizontalGroup(
            regipanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regipanel2Layout.createSequentialGroup()
                .addGroup(regipanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(regipanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(regisname, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(regipanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(regipanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2)
                            .addComponent(reginame)
                            .addComponent(jSeparator1)
                            .addComponent(regiusername, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(regipassword)
                            .addComponent(nameregi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regipass, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3)))
                    .addGroup(regipanel2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jButton1)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        regipanel2Layout.setVerticalGroup(
            regipanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regipanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(regisname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameregi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reginame, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regiusername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regipass, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regipassword, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout regipanelLayout = new javax.swing.GroupLayout(regipanel);
        regipanel.setLayout(regipanelLayout);
        regipanelLayout.setHorizontalGroup(
            regipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regipanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regipanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        regipanelLayout.setVerticalGroup(
            regipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regipanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regipanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        getContentPane().add(regipanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 330, 380));

        homelevel.setIcon(new javax.swing.ImageIcon("/home/sourav/Downloads/oie_3115507uckPCox.jpg")); // NOI18N
        getContentPane().add(homelevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regisnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regisnameActionPerformed

    private void reginameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reginameActionPerformed
        
    }//GEN-LAST:event_reginameActionPerformed

    private void regiusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regiusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regiusernameActionPerformed

    private void regipasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regipasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regipasswordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            File f=new File("testloginfo.txt");
            FileWriter fw=new FileWriter(f);
           // Scanner sc=new Scanner(System.in);
           String name=reginame.getText();
            fw.write(name);
            fw.write("\r\n");
            String username=regiusername.getText();
            fw.write(username);
            fw.write("\r\n");
            String password=regipassword.getText();
            fw.write(password);
            fw.write("\r\n");
            
            //System.out.println("done");
            fw.close();
        }
        catch(Exception e){
            System.out.println("Not found");
        }
        JOptionPane.showMessageDialog(this,"Data Stored.Ok to go");
        NewJFrameforhalkhata ob=new NewJFrameforhalkhata();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel homelevel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel nameregi;
    private javax.swing.JTextField reginame;
    private javax.swing.JPanel regipanel;
    private javax.swing.JPanel regipanel2;
    private javax.swing.JLabel regipass;
    private javax.swing.JTextField regipassword;
    private javax.swing.JTextField regisname;
    private javax.swing.JTextField regiusername;
    // End of variables declaration//GEN-END:variables
}
